server:
  log_level: info
  http_listen_port: 12345
prometheus:
  wal_directory: /tmp/wal
  global:
    scrape_interval: 15s
integrations:
  node_exporter:
    enabled: true

  prometheus_remote_write:
   - url: https://prometheus-xxxx.net/api/prom/push
     basic_auth:
       username: xxxx
       password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
